add badge
KamiN1921/test-guru pull request #20
Opened 2022-05-31 19:58 UTC by KamiN1921

2022-06-05 18:37 UTC, BubuntuClu requested changes

2022-06-05 18:37 UTC, BubuntuClu commented on app/assets/javascripts/utilities/show_params_field.js
> +    switch (rule){
чем больше правил будет, тем больше будет этот свитч. точно нельзя переделать логику того что показывать и прятать надо?

2022-06-05 18:37 UTC, BubuntuClu commented on app/services/achivments_service.rb
> +      @user.badges.push(@badges) if @badges.any?
тут проверяешь есть ли баджи и строкой ниже о5 проверяешь. как-то неоптимально.

2022-06-05 18:37 UTC, BubuntuClu commented on app/services/achivments_service.rb
> +      @badges.any?
может сервису вернуть баджи, а в том месте где ты вызываешь сервис уже делать обработку на то есть они или нет. сейчас криво выглядит что ты вызываешь метод `call` а он тебе возвращает `true/false`

2022-06-05 18:37 UTC, BubuntuClu commented on db/migrate/20220516123357_create_badges.rb
> +      t.integer :param
предлагаю сделать это поле стрингом, чтобы тут можно было хранить название категории. а если надо хранить число, то хранишь строкой, но в правиле где нужно число, конвертишь параметр из строки в число

2022-06-05 18:37 UTC, BubuntuClu commented on app/views/layouts/_footer.erb
> +    <% if current_user.is_a?(Admin) %>
`current_user.admin?`

2022-06-05 18:37 UTC, BubuntuClu commented on app/services/achivments_service.rb
> +    def completed_category(category_level)
кажется, тут путаница в нейминге параметров. уровня у категории нет. передавай сюда название категории

2022-06-05 18:37 UTC, BubuntuClu commented on app/services/achivments_service.rb
> +      @result.completed? && (Result.where(user: @user, test: @test).count <= 1)
сейчас условие неправильное. если ты не пройдешь тест, то ты получишь награду за первый провал. `completed?`вернет `true` так как текущий вопрос пуст. а второе выражение тоже вернет `true`.

1 - нужно проверять что тест пройден успешно, а не просто пройден
2 - и давай лучше пропишем `== 1`. странно выглядит условие в текущем варианте

2022-06-05 18:37 UTC, BubuntuClu commented on app/services/achivments_service.rb
> +    def user_success_results(tests)
можно добавить мемоизацию(сохранение результата), чтобы не прогонять этот запрос дважды
```
def user_success_results(tests)
     return @user_success_results if defined?(@user_success_results)

     @user_success_results = Result.where(user: @user, test_id: tests, clear: true).pluck(:test_id).uniq.count
end
```


есть еще упрощенный вариант

```
def user_success_results(tests)
     @user_success_results ||= Result.where(user: @user, test_id: tests, clear: true).pluck(:test_id).uniq.count
end
```


но в них есть разница, по разному обрабатывают ситуацию когда в переменной будет `nil`. `defined?` смотрит на объявление переменной, а `||=` сравнивает по значению(или если просто через `if @user_success_results` делать проверку)

2022-06-05 18:37 UTC, BubuntuClu commented on app/services/achivments_service.rb
> +      Badge.where.not(param: nil).select do |badge|
почему тут используешь `select`?

2022-06-05 18:37 UTC, BubuntuClu commented on app/services/achivments_service.rb
> +      Result.where(user: @user, test_id: tests, clear: true)
кажется `clear` это не то поле, что тебе надо использовать. у тебя это показатель того что тест завершен, но не показатель того что он завершен успешно

2022-06-05 18:37 UTC, BubuntuClu commented on app/controllers/results_controller.rb
> +      if achivment_service.call
вообще вызывать сервис есть смысл только в том случае если тест пройден успешно. иначе данные не изменятся с прошлого прогона сервиса.

2022-06-06 12:23 UTC, KamiN1921 commented on app/services/achivments_service.rb
> +      @user.badges.push(@badges) if @badges.any?
Это косяк мерджей. Пропустила при ручном объединении веток.

2022-06-11 16:41 UTC, BubuntuClu commented on app/controllers/results_controller.rb
> +        binding.pry
за этим надо следить, если такое задеплоить то сервак умрет

2022-06-11 16:41 UTC, BubuntuClu commented on app/models/result.rb
> +    self.update!({clear:true})
почему бэнг метод?

2022-06-13 15:59 UTC, merged